name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Material
      run: pip install git+https://${{ secrets.ACCESS_TOKEN }}@github.com/webrcade/mkdocs-material-insiders.git

    - name: Build Documentation
      run: mkdocs build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: site

    - name: Deploy to GitHub pages (main)
      uses: JamesIves/github-pages-deploy-action@releases/v3
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: main
        BRANCH: gh-pages
        FOLDER: site
